name: publish

on:
  push:
    tags:
      - "*"
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  publish:
    name: "Build and Publish container image"
    runs-on: ubuntu-latest
    env:
      release: ${{ github.ref_type == 'tag' && github.ref_name || '' }}
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4

    - name: Set up Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: GHCR Login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish container (latest)
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/cycoresystems/audimance-demo:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish container (tag)
      uses: docker/build-push-action@v6
      if: env.release != ''
      with:
        push: true
        tags: ghcr.io/cycoresystems/audimance-demo:${{ env.release }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
